### PR TITLE
i fixed the linez

### PR DESCRIPTION
**Pull request by sabianroberts**

### CODE REVIEW

**Comment by sabianroberts** [comment]
merge it

**Comment by sabianroberts** [comment]
now

**Comment by glitchgod0** [comment]
NO YOU HAVENT. IDIOT GET GOOD IM GONNA POO

**Comment by sabianroberts** [comment]
fuck sake

**Comment by glitchgod0** [comment]
Please Do Not Swear On My GitHub Profile Its Racism

**Comment by glitchgod0** [comment]
SMH

**Comment by sabianroberts** [comment]
shut up you cracker

**Comment by sabianroberts** [comment]
scrub, get good at git

**Comment by ry13y04** [comment]
glitchgod0's repository. contribute here!

**Comment by sabianroberts** [comment]
No. He refuses to merge my PR.

**Comment by glitchgod0** [comment]
FINE

**Comment by ry13y04** [comment]
glitchgod0's repository. contribute here! you may start a pull request, isue, contribution, talk, and more.

**Comment by glitchgod0** [comment]
JK

**Comment by ry13y04** [comment]
wait had camera flipped

**Pull request merged**
